FROM <%= from %>

LABEL "org.opencontainers.image.created"="<%= created %>"
LABEL "org.opencontainers.image.authors"="Joan Lloret <juallom@gmail.com>"
LABEL "org.opencontainers.image.url"="https://github.com/juallom/docker-library/packages/<%= name %>"
LABEL "org.opencontainers.image.source"="https://github.com/juallom/docker-library"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.title"="<%= name %>"
LABEL "org.opencontainers.image.description"="<%= description %>"
