name: Publish docker library images to Github Packages (ghcr.io)
on:
  push:
    branches:
      - 'main'
    tags:
      - '*_*'
  schedule:
#    - cron: '5 0 * * 0,3'
    - cron: '45 * * * *'
env:
  REGISTRY: ghcr.io
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'schedule' || ( github.event_name == 'push' && contains(github.ref_name, '_') ) }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: npm install

      - name: Publish all docker images
        if: ${{ github.event_name == 'schedule' }}
        run: npx nx run-many --target=publish --all

      - uses: actions/github-script@v6
        id: package_name
        if: ${{ github.event_name == 'push' && contains(github.ref_name, '_') }}
        with:
          script: return process.env.GITHUB_REF_NAME.split('_')[0]
          result-encoding: string

      - name: Release image
        if: ${{ github.event_name == 'push' && steps.package_name.outputs.result }}
        run: npx nx publish "${{ steps.package_name.outputs.result }}"
