name: Build
# This workflow is triggered on pushes to the repository.
on: [push]
env:
  REGISTRY: ghcr.io
jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Install Dependencies'
        run: npm i

      - name: 'Publish docker images'
        run: npx nx run-many --target=publish --all
